[package]
name = "tgif"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
x11 = { version = "2.18.2", features = ["xlib"]}
gif = "0.10.3"
chrono = "0.4.11"
rprompt = "1.0.5"
device_query = "0.2.4"
ctrlc = { version = "3.1.4", features = ["termination"] }

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
# lto = true
# codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
