[package]
name = "tgif"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

[features]
ski = ["gifski", "imgref", "rgb"]

[dependencies]
clap = "2.33.0"
x11 = { version = "2.18.2", features = ["xlib"]}
gif = "0.10.3"
chrono = "0.4.11"
rprompt = "1.0.5"
device_query = "0.2.4"
ctrlc = { version = "3.1.4", features = ["termination"] }
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.8"
image = "0.23.5"
enigo = "0.0.14"
bytesize = "1.0.1"
gifski = { version = "0.10.4", optional = true }
imgref = { version = "1.6.1", optional = true }
rgb = { version = "0.8.18", optional = true }

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
# lto = true
# codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
