[package]
name = "tgif"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

[features]
default = []
ski = ["gifski", "imgref", "rgb"] # use gifski encoder
test_ws = [] # test window system

[dependencies]
x11 = { version = "2.18.2", features = ["xlib"] }
gif = "0.11.1"
chrono = "0.4.19"
rprompt = "1.0.5"
device_query = "0.2.5"
ctrlc = { version = "3.1.7", features = ["termination"] }
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.11"
image = "0.23.10"
bytesize = "1.0.1"
gifski = { version = "1.2.1", optional = true }
imgref = { version = "1.7.0", optional = true }
rgb = { version = "0.8.25", optional = true }
dirs = "3.0.1"
natord = "1.0.9"
dominant_color = "0.3.0"
hex = "0.4.2"
kamadak-exif = "0.5.2"
colored = "2.0.0"
rust-ini = "0.16.0"

[dev-dependencies]
pretty_assertions = "0.6.1"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
# lto = true
# codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
