[package]
name = "menyoki"
version = "0.1.2"
description = "Screen{shot,cast} and perform ImageOps on the command line"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
documentation = "https://github.com/orhun/menyoki/blob/master/README.md"
homepage = "https://menyoki.cli.rs"
repository = "https://github.com/orhun/menyoki"
keywords = ["screenshot", "screencast", "gif", "recorder", "image"]
categories = ["multimedia", "graphics", "command-line-utilities"]
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]
edition = "2018"

[features]
default = []
# use the gifski encoder
ski = ["gifski", "imgref", "rgb"]
# run window system tests
test-ws = []

[target.'cfg(windows)'.dependencies]
# Windows dependencies

[target.'cfg(target_os = "macos")'.dependencies]
# MacOS dependencies

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
x11 = { version = "2.18.2", features = ["xlib"] }
textwidth = "2.1.0"

[dependencies]
# window system
device_query = "0.2.5"
ctrlc = { version = "3.1.7", features = ["termination"] }
# image operations
image = "0.23.11"
gif = "0.11.1"
kamadak-exif = "0.5.2"
dominant_color = "0.3.0"
gifski = { version = "1.2.2", optional = true }
imgref = { version = "1.7.0", optional = true }
rgb = { version = "0.8.25", optional = true }
# utility
dirs = "3.0.1"
rust-ini = "0.16.0"
chrono = "0.4.19"
hex = "0.4.2"
bytesize = "1.0.1"
natord = "1.0.9"
colored = "2.0.0"
log = "0.4.11"
fern_colored = { version = "0.6.1", features = ["colored"] }

[dependencies.clap]
version = "2.33.3"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
pretty_assertions = "0.6.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
