[package]
name = "tgif"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
x11 = "2.18.2"

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[profile.bench]
opt-level = 3
debug = false
