name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends --allow-unauthenticated libx11-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
          override: true
      - name: Build the project
        run: PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --locked --target ${{ matrix.TARGET }}
      - name: Prepare assets
        run: |
          mkdir assets
          cp -t assets/ target/${{ matrix.TARGET }}/release/menyoki && strip -s assets/menyoki
          cp -t assets/ LICENSE README.md CHANGELOG.md
          cp -t assets/ --parents man/*
          cp -t assets/ --parents completions/* && rm -f assets/completions/generate.sh
          cp -t assets/ --parents config/menyoki.conf
          mv assets/ menyoki-${{ env.RELEASE_VERSION }}/
          tar -czvf menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz menyoki-${{ env.RELEASE_VERSION }}
          sha512sum menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz > menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz.sha512
          echo "${{ secrets.GPG_RELEASE_KEY }}" | base64 --decode > release.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback --passphrase-fd 0 --import release.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback --passphrase-fd 0 --detach-sign menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz
            menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz.sig
            menyoki-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz.sha512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare release notes
        run: echo -e "$img\n$text" > RELEASE.txt
        env:
          img: '<a href="https://github.com/orhun/menyoki"><img src="https://user-images.githubusercontent.com/24392180/98470768-09356680-21f9-11eb-81de-94a622b32db4.png" width="300"></a>'
          text: 'See [**changelog**](https://github.com/orhun/menyoki/blob/master/CHANGELOG.md) for release notes.'
      - name: Set release details
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: RELEASE.txt
          is_append_body: false

  publish-crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --locked --token ${{ secrets.CARGO_TOKEN }}
